<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matías Deneken">
<meta name="dcterms.date" content="2026-04-19">
<meta name="keywords" content="elite networks, Latin America, family, political sociology, Wikipedia, social network analysis">

<title>Elite Family Networks and the Reproduction of Political Power in Latin America</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="elite_networks_paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="elite_networks_paper_files/libs/quarto-html/quarto.js"></script>
<script src="elite_networks_paper_files/libs/quarto-html/popper.min.js"></script>
<script src="elite_networks_paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="elite_networks_paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="elite_networks_paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="elite_networks_paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="elite_networks_paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="elite_networks_paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="elite_networks_paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="elite_networks_paper_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="elite_networks_paper_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-marco" id="toc-sec-marco" class="nav-link" data-scroll-target="#sec-marco"><span class="header-section-number">2</span> Literature and theoretical background</a>
  <ul class="collapse">
  <li><a href="#notable-families-oligarchy-and-the-state" id="toc-notable-families-oligarchy-and-the-state" class="nav-link" data-scroll-target="#notable-families-oligarchy-and-the-state"><span class="header-section-number">2.1</span> Notable families, oligarchy, and the state</a></li>
  <li><a href="#network-topology-and-political-orders" id="toc-network-topology-and-political-orders" class="nav-link" data-scroll-target="#network-topology-and-political-orders"><span class="header-section-number">2.2</span> Network topology and political orders</a></li>
  <li><a href="#empire-corridor-and-transnational-elites" id="toc-empire-corridor-and-transnational-elites" class="nav-link" data-scroll-target="#empire-corridor-and-transnational-elites"><span class="header-section-number">2.3</span> Empire, corridor, and transnational elites</a></li>
  <li><a href="#gender-marriage-and-visibility" id="toc-gender-marriage-and-visibility" class="nav-link" data-scroll-target="#gender-marriage-and-visibility"><span class="header-section-number">2.4</span> Gender, marriage, and visibility</a></li>
  </ul></li>
  <li><a href="#sec-diseno" id="toc-sec-diseno" class="nav-link" data-scroll-target="#sec-diseno"><span class="header-section-number">3</span> Data and methods</a>
  <ul class="collapse">
  <li><a href="#source-and-population" id="toc-source-and-population" class="nav-link" data-scroll-target="#source-and-population"><span class="header-section-number">3.1</span> Source and population</a></li>
  <li><a href="#network-construction-and-metrics" id="toc-network-construction-and-metrics" class="nav-link" data-scroll-target="#network-construction-and-metrics"><span class="header-section-number">3.2</span> Network construction and metrics</a>
  <ul class="collapse">
  <li><a href="#why-betweenness-is-computed-on-the-multiplex-graph" id="toc-why-betweenness-is-computed-on-the-multiplex-graph" class="nav-link" data-scroll-target="#why-betweenness-is-computed-on-the-multiplex-graph"><span class="header-section-number">3.2.1</span> Why betweenness is computed on the multiplex graph</a></li>
  </ul></li>
  <li><a href="#analytical-stance-and-temporal-scope" id="toc-analytical-stance-and-temporal-scope" class="nav-link" data-scroll-target="#analytical-stance-and-temporal-scope"><span class="header-section-number">3.3</span> Analytical stance and temporal scope</a></li>
  <li><a href="#sec-limitaciones" id="toc-sec-limitaciones" class="nav-link" data-scroll-target="#sec-limitaciones"><span class="header-section-number">3.4</span> Limitations (explicit)</a></li>
  </ul></li>
  <li><a href="#sec-resultados" id="toc-sec-resultados" class="nav-link" data-scroll-target="#sec-resultados"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#h1-family-closure-and-political-concentration" id="toc-h1-family-closure-and-political-concentration" class="nav-link" data-scroll-target="#h1-family-closure-and-political-concentration"><span class="header-section-number">4.1</span> H1: Family closure and political concentration</a></li>
  <li><a href="#h2-topology-and-stylized-regime-types" id="toc-h2-topology-and-stylized-regime-types" class="nav-link" data-scroll-target="#h2-topology-and-stylized-regime-types"><span class="header-section-number">4.2</span> H2: Topology and stylized regime types</a></li>
  <li><a href="#h3-transnational-corridors" id="toc-h3-transnational-corridors" class="nav-link" data-scroll-target="#h3-transnational-corridors"><span class="header-section-number">4.3</span> H3: Transnational corridors</a></li>
  <li><a href="#h4-betweenness-and-brokerage" id="toc-h4-betweenness-and-brokerage" class="nav-link" data-scroll-target="#h4-betweenness-and-brokerage"><span class="header-section-number">4.4</span> H4: Betweenness and brokerage</a></li>
  <li><a href="#gender-patterns" id="toc-gender-patterns" class="nav-link" data-scroll-target="#gender-patterns"><span class="header-section-number">4.5</span> Gender patterns</a></li>
  </ul></li>
  <li><a href="#sec-discusion" id="toc-sec-discusion" class="nav-link" data-scroll-target="#sec-discusion"><span class="header-section-number">5</span> Discussion and conclusion</a>
  <ul class="collapse">
  <li><a href="#heterogeneity-versus-a-single-latin-american-model" id="toc-heterogeneity-versus-a-single-latin-american-model" class="nav-link" data-scroll-target="#heterogeneity-versus-a-single-latin-american-model"><span class="header-section-number">5.1</span> Heterogeneity versus a single Latin American model</a></li>
  <li><a href="#the-pacific-corridor" id="toc-the-pacific-corridor" class="nav-link" data-scroll-target="#the-pacific-corridor"><span class="header-section-number">5.2</span> The Pacific corridor</a></li>
  <li><a href="#alternative-explanations-and-their-limits" id="toc-alternative-explanations-and-their-limits" class="nav-link" data-scroll-target="#alternative-explanations-and-their-limits"><span class="header-section-number">5.3</span> Alternative explanations and their limits</a></li>
  <li><a href="#wikipedia-as-archive-not-mirror" id="toc-wikipedia-as-archive-not-mirror" class="nav-link" data-scroll-target="#wikipedia-as-archive-not-mirror"><span class="header-section-number">5.4</span> Wikipedia as archive, not mirror</a></li>
  <li><a href="#ethics-and-public-use" id="toc-ethics-and-public-use" class="nav-link" data-scroll-target="#ethics-and-public-use"><span class="header-section-number">5.5</span> Ethics and public use</a></li>
  <li><a href="#toward-causal-identification-design-proposals" id="toc-toward-causal-identification-design-proposals" class="nav-link" data-scroll-target="#toward-causal-identification-design-proposals"><span class="header-section-number">5.6</span> Toward causal identification: design proposals</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks"><span class="header-section-number">5.7</span> Concluding remarks</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="elite_networks_paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Elite Family Networks and the Reproduction of Political Power in Latin America</h1>
<p class="subtitle lead">Evidence from Wikipedia Genealogical Data, Nineteenth to Twenty-First Centuries</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Matías Deneken </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            [Institution]
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>elite networks, Latin America, family, political sociology, Wikipedia, social network analysis</p>
  </div>
</div>

</header>


<section id="abstract" class="level1 unnumbered">
<h1 class="unnumbered">Abstract</h1>
<p>How do elite family networks structure the reproduction of political power in Latin America across the long nineteenth to twenty-first centuries? Using genealogical data scraped from Spanish-language Wikipedia for 6,169 notable individuals across ten countries, we construct kinship networks based on spouse, parent–child, and partner ties (8,201 matched edges between identified individuals). We combine network topology measures—degree, betweenness, PageRank, and Louvain community detection—with country-level aggregates of endogamy, transnational reach, and dynasty persistence. Descriptive and correlational analyses speak to four hypotheses: (H1) family closure covaries with political concentration; (H2) macro-scale network topology (chain, star, web, fragment) aligns with stylized regime types; (H3) transnational family ties follow Pacific–Andean rather than Atlantic corridors in the aggregate; (H4) betweenness centrality identifies individuals in structural brokerage positions potentially relevant to cross-national influence. We find substantial heterogeneity across republics. The strongest cross-national weights in the documented graph link Chile–Peru and Argentina–Uruguay. We emphasize that Wikipedia encodes a <em>documentary</em> elite biased toward literate, nationally visible strata. Causal claims are hedged throughout; findings are best interpreted as structured description of a collective digital archive rather than as an exhaustive map of Latin American elites.</p>
<p><strong>Keywords:</strong> elite networks; Latin America; family; political reproduction; Wikipedia; social network analysis</p>
<div style="page-break-after: always;"></div>
</section>
<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Latin American political history has long been interpreted through the lens of oligarchy, caudillismo, and the intergenerational transmission of status (Mahoney, 2010; Centeno, 2002). Classical elite theory—from Pareto and Mosca through mid-twentieth-century political sociology—stressed circulation versus closure: whether ruling strata renew themselves through co-optation and alliance or seal themselves behind kinship and class barriers. Empirical adjudication at scale, however, has remained difficult. Systematic, comparable evidence on <em>how</em> elite families connect across countries and centuries is scarce because prosopographical reconstruction is labor-intensive and rarely harmonized across national archives.</p>
<p>Historical sociology and political sociology nevertheless offer rich idiographic traditions. Padgett and Ansell’s (1993) analysis of Florentine marriage and banking ties showed how multiplex network structure could sustain “robust action” under factional rivalry. Regional studies of Latin American <em>familias notables</em> documented marriage strategies linking land, office, and credit (Balmori, Voss, &amp; Wortman, 1984). Scaling such insights to multiple republics typically required either heroic archival work or illustrative genealogies whose representativeness is uncertain.</p>
<p>Digital traces offer a complementary path. Spanish-language Wikipedia aggregates biographical entries produced by dispersed editors; kinship statements—spouses, parents, children, partners—are often included in infoboxes or narrative leads. These data are neither representative of whole populations nor free of bias: they disproportionately document literate, urban, politically and culturally visible individuals. Yet precisely that bias may approximate what successive generations of national publics chose to record about “notable” families—a <em>documentary elite</em> whose network properties are sociologically interesting in their own right (Lazer et al., 2014). The task is not to confuse Wikipedia with society, but to analyze the structure of a large, public, repeatedly edited genealogical corpus.</p>
<p>This paper asks: <strong>How have elite family networks structured the reproduction of political power in Latin America from roughly the nineteenth through the twenty-first centuries?</strong> We articulate four hypotheses (H1–H4) linking (i) marriage closure to political concentration, (ii) macro-scale graph topology to stylized regime types, (iii) transnational kinship geography to colonial-era corridors, and (iv) betweenness centrality to brokerage positions potentially associated with cross-national salience.</p>
<p>Our contribution is threefold, but rests on a single organizing claim: <strong>family network structure is not a byproduct of political order in Latin America—it is a constitutive infrastructure of it.</strong> Where elites built durable states, they did so by layering kinship closure onto institutional access; where states remained fragile or personalist, the kinship graph itself encodes why. This claim does not require causal identification to be useful: demonstrating that network topology <em>covaries systematically</em> with regime type across ten republics, using a common corpus and comparable metrics, is itself a contribution that archival prosopography has rarely achieved at this scale.</p>
<p>We introduce two conceptual distinctions that organize the analysis. First, we distinguish <strong>closure</strong> from <strong>reach</strong> as alternative elite network strategies: families that maximize endogamy (closure) sacrifice the bridging ties needed for transnational coordination, while families that maximize cross-border reach typically exhibit lower endogamy rates. This <strong>closure–reach trade-off</strong> is observable in degree–endogamy correlations and is theoretically grounded in the tension between Bourdieu’s (1996) reproductive closure and Granovetter’s (1973) structural holes. Second, we distinguish the <strong>documentary elite field</strong>—the stratum of families that have successfully inscribed themselves in public digital archives—from the broader social elite. The documentary elite field is the object we analyze; its boundaries are themselves a sociological datum, not merely a sampling limitation.</p>
<p>The remainder proceeds as follows. <a href="#sec-marco" class="quarto-xref">Section&nbsp;2</a> reviews relevant literature. <a href="#sec-diseno" class="quarto-xref">Section&nbsp;3</a> describes data construction, variables, and limitations—with summary statistics in <a href="#tbl-corpus" class="quarto-xref">Table&nbsp;1</a> and related tables. <a href="#sec-resultados" class="quarto-xref">Section&nbsp;4</a> presents results by hypothesis, embedding the main empirical tables and figures in the narrative. <a href="#sec-discusion" class="quarto-xref">Section&nbsp;5</a> discusses interpretation and scope conditions, then concludes.</p>
</section>
<section id="sec-marco" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Literature and theoretical background</h1>
<section id="notable-families-oligarchy-and-the-state" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="notable-families-oligarchy-and-the-state"><span class="header-section-number">2.1</span> Notable families, oligarchy, and the state</h2>
<p>Classic scholarship on Latin America emphasized the <em>familia notable</em> as a unit linking land, urban property, marriage, and access to state office (Balmori et al., 1984). Centeno (2002) connected elite networks to war-making and the fiscal–military organization of republics; Mahoney (2010) emphasized path dependence in colonial and postcolonial institutions. These works imply testable expectations at the network level: <strong>family strategies</strong>—endogamy, strategic exogamy, and placement of kin in parties and ministries—should covary with how concentrated political access is and how durable elite coalitions prove over time.</p>
<p>Bourdieu’s (1996) analysis of the French state nobility supplies a vocabulary for <strong>social reproduction</strong>: elites convert economic resources into social ties and cultural credentials, then monopolize institutional positions across generations. Latin American contexts differ—Catholic Church, army, export agriculture, mining enclaves—but the <em>problem</em> of stabilizing advantage through kinship remains analogous. Where elites successfully restrict marriage markets, one expects measurable <strong>closure</strong> at the level of surname clusters (H1). Where party systems fragment elite access, closure may remain moderate even as network density rises.</p>
</section>
<section id="network-topology-and-political-orders" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="network-topology-and-political-orders"><span class="header-section-number">2.2</span> Network topology and political orders</h2>
<p>Historical network analysis demonstrates that <strong>macro-structure</strong>—chains, stars, dense cores, or disconnected fragments—can correspond to distinct modes of coordination and conflict (Padgett &amp; Ansell, 1993). Granovetter (1973) motivated attention to weak ties and brokers bridging clusters. Translating these ideas to Latin America requires caution: one may <em>loosely</em> associate linear dynastic chains with personalist or patrimonial consolidation (Weber’s patrimonialism as ideal type), star-like graphs with a legitimating “founding” lineage, dense webs with competitive oligarchy and multiple channels of access, and fragmented graphs with regionalized or weakly integrated national elites. Such mappings are <strong>stylized ideal-types</strong> for interpretation, not operational codes inferred mechanically from graph metrics (H2).</p>
</section>
<section id="empire-corridor-and-transnational-elites" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="empire-corridor-and-transnational-elites"><span class="header-section-number">2.3</span> Empire, corridor, and transnational elites</h2>
<p>Colonial geography—mining belts, highland–coastal links, viceregal capitals—may channel later elite mobility and marriage. Pacific Andean spaces and Chilean–Peruvian histories of war and diplomacy plausibly leave <strong>residual structure</strong> in cross-border kinship long after independence. If transnational kinship edges in a Wikipedia-derived graph concentrate along a Pacific–Andean corridor rather than dispersing uniformly, that pattern offers descriptive support for <strong>path-dependent geography</strong> (H3)—not proof of a colonial causal mechanism, but consistency with historically informed priors.</p>
</section>
<section id="gender-marriage-and-visibility" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="gender-marriage-and-visibility"><span class="header-section-number">2.4</span> Gender, marriage, and visibility</h2>
<p>Colonial and republican marriage regimes structured women’s positions as alliance partners and transmitters of property and status (Lavrin, 1990). If encyclopedic records disproportionately document women through ties to notable husbands and sons, <strong>degree</strong> in a kin-only graph may overstate public-political centrality while <strong>betweenness</strong> on office-weighted projections remains low. We treat gendered splits between degree and betweenness as <strong>hypothesis-generating</strong> evidence about brokerage and exclusion, not as definitive proof of mechanisms.</p>
</section>
</section>
<section id="sec-diseno" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data and methods</h1>
<section id="source-and-population" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="source-and-population"><span class="header-section-number">3.1</span> Source and population</h2>
<p>We scraped Spanish-language Wikipedia biographical pages for ten Latin American countries (Argentina, Bolivia, Chile, Colombia, Ecuador, Mexico, Paraguay, Peru, Uruguay, and Venezuela), following the project pipeline described in the replication repository. Raw extracts were consolidated and normalized into relational tables (<code>personas</code>, <code>relaciones</code>, <code>partidos</code>, <code>educacion</code>, <code>sucesiones</code>). <a href="#tbl-corpus" class="quarto-xref">Table&nbsp;1</a> summarizes the distribution of retained individuals by <code>pais_base</code> after deduplication. The working person table contains <strong>6,169</strong> rows; <strong>8,201</strong> kinship relation rows link two identified individuals (<code>persona_relacionada_id</code> non-missing) out of <strong>14,190</strong> extracted rows, so <strong>57.8%</strong> of raw kinship statements resolve to another scraped biography. <strong>92.9%</strong> of persons have a parsed birth year (<code>anio_nacimiento</code>), which anchors descriptive temporal plots.</p>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-corpus" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-corpus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Corpus coverage: individuals by country (pais_base) in the normalized person table.
</figcaption>
<div aria-describedby="tbl-corpus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Individuals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chile</td>
<td style="text-align: right;">1371</td>
</tr>
<tr class="even">
<td style="text-align: left;">colombia</td>
<td style="text-align: right;">1333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peru</td>
<td style="text-align: right;">1296</td>
</tr>
<tr class="even">
<td style="text-align: left;">argentina</td>
<td style="text-align: right;">1147</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mexico</td>
<td style="text-align: right;">661</td>
</tr>
<tr class="even">
<td style="text-align: left;">venezuela</td>
<td style="text-align: right;">170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uruguay</td>
<td style="text-align: right;">84</td>
</tr>
<tr class="even">
<td style="text-align: left;">ecuador</td>
<td style="text-align: right;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bolivia</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">paraguay</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p><strong>Family</strong> is operationalized via <strong><code>familia_norm</code></strong>, a normalized surname cluster produced by the processing pipeline (orthographic merging). This is a Wikipedia-assigned label, not a validated genealogical house. <strong>Country</strong> attaches to individuals using nationality fields, infobox cues, text-based detection, and manual overrides (<code>url_pais_extra.csv</code>). A kinship edge is treated as <strong>transnational</strong> in aggregations when endpoint countries differ under these assignments.</p>
</section>
<section id="network-construction-and-metrics" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="network-construction-and-metrics"><span class="header-section-number">3.2</span> Network construction and metrics</h2>
<p>We construct an undirected graph on matched kinship edges and—following <code>03_grafo_parentesco.R</code>—augment it with within-family ties for small lineages, predecessor–successor links, and bipartite projections from shared party and university membership for <strong>global</strong> centrality and community detection. Thus, degree and betweenness reported in <code>metricas_centralidad.csv</code> refer to this <strong>multiplex</strong> graph, whereas marriage-based endogamy rates use kin-type edges only (see below).</p>
<section id="why-betweenness-is-computed-on-the-multiplex-graph" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="why-betweenness-is-computed-on-the-multiplex-graph"><span class="header-section-number">3.2.1</span> Why betweenness is computed on the multiplex graph</h3>
<p>Betweenness centrality in a <strong>kinship-only</strong> graph would identify individuals who structurally mediate genealogical chains—an analytically narrow concept tied to documented parent–child and spousal links alone. The <strong>multiplex</strong> graph used here layers party co-membership, shared educational institutions, and political predecessor–successor ties onto kinship edges, so that shortest paths can pass through institutional as well as familial channels. That specification better approximates the <strong>multi-dimensional social infrastructure</strong> through which elite coordination is plausibly sustained in historical and republican settings (office holding, party politics, and university training alongside marriage). Endogamy rates, by contrast, are computed on spouse and partner edges only, preserving a strictly <strong>matrimonial</strong> definition of family closure. Metrics were computed in <strong>R</strong> with <strong>igraph</strong>; edges were constructed and merged as documented in the replication scripts.</p>
<p>Metrics computed with <strong>igraph</strong> include degree, betweenness centrality, PageRank, local clustering, and Louvain communities (resolution 1.0). <strong>Endogamy:</strong> on spouse/partner edges with matched partners, a tie is endogamous if both endpoints share <code>familia_norm</code>. Country-level marriage counts and rates are reported in <a href="#tbl-endogamia" class="quarto-xref">Table&nbsp;2</a>. <strong>Transnational structure:</strong> country-pair aggregates combine kinship and biographical “mention” signals (<code>transnacional_red_paises.csv</code>). <strong>Dynasty persistence</strong> is summarized in <code>dinastias_persistencia.csv</code>. Hypothesis-oriented country summaries are pre-computed in <code>paper/tables/T02_h1_h4_resumen_pais.csv</code> and reproduced as <a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a>.</p>
</section>
</section>
<section id="analytical-stance-and-temporal-scope" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="analytical-stance-and-temporal-scope"><span class="header-section-number">3.3</span> Analytical stance and temporal scope</h2>
<p>All main analyses are <strong>observational</strong>. Network metrics describe co-occurrence in a digital corpus conditioned on notability and editorial practice. Language in <a href="#sec-resultados" class="quarto-xref">Section&nbsp;4</a> follows a <strong>hedging norm</strong> (“associated with,” “consistent with,” “suggestive”). Biographical dates span roughly <strong>1800–2000</strong> with colonial antecedents for some lineages; long-run graphs <strong>conflate</strong> periods unless cohorts are split explicitly.</p>
</section>
<section id="sec-limitaciones" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-limitaciones"><span class="header-section-number">3.4</span> Limitations (explicit)</h2>
<ol type="1">
<li><strong>Selection bias:</strong> Wikipedia encodes literate, visible, often male elites; indigenous, Afro-descendant, and subnational elites are systematically underrepresented.</li>
<li><strong>Kinship incompleteness:</strong> editors omit relatives; women may appear chiefly as spouses or mothers.</li>
<li><strong>Label noise:</strong> <code>familia_norm</code> may merge or split lineages incorrectly, especially across countries.</li>
<li><strong>Temporal conflation:</strong> graphs pool republican and colonial-era ties unless disaggregated.</li>
<li><strong>Edge incompleteness:</strong> <strong>42.2%</strong> of kinship rows lack a matched endpoint; covert patronage or business ties are invisible.</li>
<li><strong>Single-country assignment</strong> forces multinational biographies into one country, partially mitigated by manual overrides and biographical mention layers.</li>
<li><strong>No causal identification:</strong> betweenness or endogamy cannot be interpreted as manipulable treatments without additional design.</li>
</ol>
<p>These limitations frame the contribution as a <strong>mapped documentary elite</strong>—not an exhaustive social register—and motivate the interpretive discipline maintained in <a href="#sec-resultados" class="quarto-xref">Section&nbsp;4</a> and <a href="#sec-discusion" class="quarto-xref">Section&nbsp;5</a>.</p>
</section>
</section>
<section id="sec-resultados" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<p>We organize results by hypothesis. Summary statistics for marriage closure and institutional concentration by country appear in <a href="#tbl-endogamia" class="quarto-xref">Table&nbsp;2</a> and <a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a>. Cross-border structure is documented in <a href="#tbl-pairs" class="quarto-xref">Table&nbsp;4</a> and <a href="#tbl-families-multinational" class="quarto-xref">Table&nbsp;5</a>. <a href="#fig-temporal-by-country" class="quarto-xref">Figure&nbsp;1</a> situates the temporal distribution of births used throughout. National network layouts and transnational aggregates are shown in <a href="#fig-facet" class="quarto-xref">Figure&nbsp;2</a> through <a href="#fig-mapa-circle" class="quarto-xref">Figure&nbsp;5</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-temporal-by-country" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temporal-by-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../outputs/figures/dinastias_temporal_por_pais.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temporal-by-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Birth year distribution by country (kernel density ridges; documented individuals with non-missing birth year).
</figcaption>
</figure>
</div>
</div>
</div>
<section id="h1-family-closure-and-political-concentration" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="h1-family-closure-and-political-concentration"><span class="header-section-number">4.1</span> H1: Family closure and political concentration</h2>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-endogamia" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-endogamia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Marriage records and endogamy rates by country (matched partners; kinship-based definitions).
</figcaption>
<div aria-describedby="tbl-endogamia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Marriages</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Endogamous</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Endogamy rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Transnational marriages</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Transnational rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.900</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0.870</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">177</td>
<td style="text-align: right;">153</td>
<td style="text-align: right;">0.864</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">0.203</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Venezuela</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0.840</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.200</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">251</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">0.837</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.092</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">151</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0.795</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uruguay</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.778</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.389</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0.769</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.115</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.667</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-h1h4" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-h1h4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Country-level family counts and descriptive correlations between genealogical degree and family closure (paper summary table).
</figcaption>
<div aria-describedby="tbl-h1h4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Families (n)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Median party conc.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Median office conc.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Corr(degree, closure)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Corr(betweenness, closure)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">165</td>
<td style="text-align: left;">0.500</td>
<td style="text-align: left;">0.500</td>
<td style="text-align: left;">-0.738</td>
<td style="text-align: left;">-0.236</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.417</td>
<td style="text-align: left;">0.550</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">98</td>
<td style="text-align: left;">0.375</td>
<td style="text-align: left;">0.529</td>
<td style="text-align: left;">-0.536</td>
<td style="text-align: left;">-0.330</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">147</td>
<td style="text-align: left;">0.667</td>
<td style="text-align: left;">0.556</td>
<td style="text-align: left;">-0.478</td>
<td style="text-align: left;">-0.073</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">0.700</td>
<td style="text-align: left;">0.472</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">111</td>
<td style="text-align: left;">0.667</td>
<td style="text-align: left;">0.667</td>
<td style="text-align: left;">-0.797</td>
<td style="text-align: left;">-0.440</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">1.000</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">182</td>
<td style="text-align: left;">0.500</td>
<td style="text-align: left;">0.571</td>
<td style="text-align: left;">-0.720</td>
<td style="text-align: left;">-0.122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uruguay</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">0.833</td>
<td style="text-align: left;">0.615</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Venezuela</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">0.500</td>
<td style="text-align: left;">0.625</td>
<td style="text-align: left;">-0.764</td>
<td style="text-align: left;">-0.344</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note. </span> <sup></sup> Correlations are not reported for countries with fewer than 10 families</td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>Endogamy rates vary markedly across countries (<a href="#tbl-endogamia" class="quarto-xref">Table&nbsp;2</a>). Large republics cluster between roughly <strong>0.77 and 0.87</strong> on the kinship-based endogamy rate, with <strong>Paraguay</strong> at <strong>1.00</strong> on a very small marriage count (<strong>4</strong>). <strong>Bolivia</strong> shows the lowest endogamy rate in the table (<strong>0.67</strong>) alongside a high transnational marriage share (<strong>0.67</strong>), reflecting both small <strong>n</strong> and boundary effects in the corpus. <a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a> reports family counts per country (e.g., <strong>Argentina 165</strong>, <strong>Peru 182</strong>, <strong>Mexico 111</strong>, <strong>Chile 98</strong>) and country-level correlations between mean genealogical degree and family closure, and between mean betweenness and closure, within families. Cells marked “—” indicate correlations that were not estimated (see table note).</p>
<p>At the country level, <strong>Corr(degree, closure)</strong> is <strong>negative</strong> everywhere it is defined in <a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a>, and substantively large for several major republics: <strong>Mexico −0.797</strong>, <strong>Venezuela −0.764</strong>, <strong>Argentina −0.738</strong>, <strong>Peru −0.720</strong>, <strong>Chile −0.536</strong>, <strong>Colombia −0.478</strong>. One <strong>observational</strong> reading—consistent with competitive-oligarchy narratives and with multiplex “robust action” (Padgett &amp; Ansell, 1993)—is that <strong>large, highly connected families could not “afford” high endogamy</strong> if maintaining network reach required outward marriage and alliance; smaller or less central lineages, by contrast, could sustain higher closure without sacrificing documented connectivity. Interpreted through Bourdieu’s (1996) vocabulary of capital conversion, brokerage across families and institutions and closure within the surname cluster appear here as <strong>alternative strategies</strong> whose joint realization is constrained in the marriage market, not as mechanically complementary dimensions.</p>
<p><strong>Corr(betweenness, closure)</strong> is <strong>more modest</strong> in magnitude than <strong>Corr(degree, closure)</strong> in every country where both are defined—for example <strong>Argentina −0.236</strong>, <strong>Mexico −0.440</strong>, <strong>Chile −0.330</strong>, <strong>Venezuela −0.344</strong>, <strong>Peru −0.122</strong>, <strong>Colombia −0.073</strong> (<a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a>)—suggesting that <strong>structural brokerage in the multiplex graph</strong> is less tightly organized around matrimonial closure than raw genealogical degree is. That pattern is consistent with institution-heavy shortest paths (party, university, succession) that need not align with endogamy rates computed on spouse/partner edges alone.</p>
<p>The negative degree–closure correlation admits a structural mechanism that goes beyond coincidence. In competitive oligarchic settings, access to state resources—contracts, appointments, fiscal transfers— required coalition partners drawn from <em>outside</em> one’s own surname cluster. Endogamy, in this context, is a luxury of the politically marginal: families secure enough in their economic base (hacienda, mining enclave, Church patronage) to forgo the brokerage rents available through exogamous alliance. Large, high-degree families in the Wikipedia corpus are disproportionately political families—presidents, ministers, generals—whose positions required permanent negotiation with rival lineages. This is consistent with Padgett and Ansell’s (1993) finding that Medici dominance depended precisely on <em>not</em> over-committing to any single faction: multiplex, outward-facing networks sustained “robust action” that dense in-group closure would have foreclosed. The pattern is descriptive, not causal; the mechanism proposed here is a hypothesis for future cohort-level testing.</p>
<p>The weaker betweenness–closure correlation has a different explanation. Betweenness in the multiplex graph reflects position on shortest paths that traverse parties, universities, and succession chains—not only kinship. An individual can be a structural broker across institutions <em>regardless</em> of whether their family is endogamous, because brokerage in the multiplex graph is determined by the <em>institutional</em> layer, not the matrimonial layer. This separation of genealogical closure from institutional brokerage is itself a substantive finding: it suggests that the two classic mechanisms of elite reproduction—marriage strategy and institutional placement—operated with considerable independence in Latin American republics, and should not be conflated analytically.</p>
<p><strong>H1 receives partial descriptive support:</strong> closure and institutional concentration co-vary in informative ways in <a href="#tbl-h1h4" class="quarto-xref">Table&nbsp;3</a>, but the degree–closure association is heterogeneous and <strong>not</strong> uniform across polities.</p>
</section>
<section id="h2-topology-and-stylized-regime-types" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="h2-topology-and-stylized-regime-types"><span class="header-section-number">4.2</span> H2: Topology and stylized regime types</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-facet" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../outputs/figures/exploracion_redes_facet.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Family kinship networks by country (exploratory faceted layouts; node size encodes degree in each subgraph).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Exploratory visualization and community structure suggest <strong>ideal-typical alignments</strong> (interpretive, not algorithmically assigned). <strong>Paraguay</strong> shows a near-linear chain around the López dynasty, evocative of patrimonial consolidation. <strong>Chile and Peru</strong> display star-like patterns with prominent hubs in exploratory plots. <strong>Argentina, Colombia, and Mexico</strong> show dense webs with multiple high-degree nodes. <strong>Bolivia, Venezuela, and Ecuador</strong> appear more fragmented into smaller cohesive clusters. <a href="#fig-facet" class="quarto-xref">Figure&nbsp;2</a> summarizes the country-faceted view used in the replication workflow. <strong>H2 is supported descriptively</strong> at the level of stylized analogy; we do not estimate predictive models from topology to regime type.</p>
</section>
<section id="h3-transnational-corridors" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="h3-transnational-corridors"><span class="header-section-number">4.3</span> H3: Transnational corridors</h2>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-pairs" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pairs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Strongest country–country ties (kinship + biographical signals), top 15 pairs by total weight.
</figcaption>
<div aria-describedby="tbl-pairs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">From → To</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kinship</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Biographical</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chile → peru</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">117</td>
</tr>
<tr class="even">
<td style="text-align: left;">argentina → uruguay</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">argentina → chile</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">94</td>
</tr>
<tr class="even">
<td style="text-align: left;">argentina → peru</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">argentina → colombia</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="even">
<td style="text-align: left;">chile → colombia</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">colombia → peru</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">colombia → venezuela</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chile → mexico</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">44</td>
</tr>
<tr class="even">
<td style="text-align: left;">argentina → mexico</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">argentina → bolivia</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">colombia → ecuador</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">colombia → mexico</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">mexico → peru</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">argentina → paraguay</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-families-multinational" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-families-multinational-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Multinational families ranked by number of countries represented (top 12 by breadth × size).
</figcaption>
<div aria-describedby="tbl-families-multinational-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Family</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Countries</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Members</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Country list</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">borrero</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">argentina, chile, colombia, ecuador</td>
</tr>
<tr class="even">
<td style="text-align: left;">campero</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">argentina, bolivia, chile, peru</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ponce de león</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">argentina, mexico, peru, uruguay</td>
</tr>
<tr class="even">
<td style="text-align: left;">garcía de zúñiga</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">argentina, chile, colombia, uruguay</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sucre</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">argentina, colombia, ecuador, venezuela</td>
</tr>
<tr class="even">
<td style="text-align: left;">pinto chile</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">argentina, chile, uruguay</td>
</tr>
<tr class="odd">
<td style="text-align: left;">caicedo</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">48</td>
<td style="text-align: left;">chile, colombia, peru</td>
</tr>
<tr class="even">
<td style="text-align: left;">velasco chile</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;">argentina, chile, venezuela</td>
</tr>
<tr class="odd">
<td style="text-align: left;">diez canseco</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">chile, ecuador, peru</td>
</tr>
<tr class="even">
<td style="text-align: left;">pizarro</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">chile, colombia, peru</td>
</tr>
<tr class="odd">
<td style="text-align: left;">miró quesada</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">mexico, peru, uruguay</td>
</tr>
<tr class="even">
<td style="text-align: left;">o'donnell</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">argentina, colombia, mexico</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-transnational-net" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-transnational-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../outputs/figures/transnacional_red_paises.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-transnational-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Transnational network between countries (cross-border kinship + biographical signals).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mapa-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mapa-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../outputs/figures/mapa_global_conexiones.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mapa-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Cross-national connections (aggregated matrix and country pairs with the most ties).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mapa-circle" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mapa-circle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../outputs/figures/mapa_global_red_paises_circulo.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mapa-circle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Country network (circular layout); one node = country, edge width = aggregated connections.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Aggregated weights rank <strong>Chile–Peru</strong> first (<strong>117</strong> total counted events), followed by <strong>Argentina–Uruguay</strong> (<strong>105</strong>), <strong>Argentina–Chile</strong> (<strong>94</strong>), and <strong>Argentina–Peru</strong> (<strong>90</strong>) (<a href="#tbl-pairs" class="quarto-xref">Table&nbsp;4</a>; <a href="#fig-transnational-net" class="quarto-xref">Figure&nbsp;3</a> through <a href="#fig-mapa-circle" class="quarto-xref">Figure&nbsp;5</a>). Atlantic-oriented pairs such as <strong>Argentina–Brazil</strong> are absent from the top of this list in the current aggregation.</p>
<p>The <strong>decomposition into kinship versus biographical counts</strong> matters theoretically. <strong>Chile–Peru</strong> combines <strong>36</strong> kinship and <strong>81</strong> biographical events—roughly <strong>31%</strong> kinship and <strong>69%</strong> biographical—so the strongest dyad in the table is driven <strong>primarily</strong> by biographical co-mention (death, residence, occupation) rather than by cross-border genealogy alone. <strong>Argentina–Chile</strong> shows the reverse emphasis: <strong>56</strong> kinship and <strong>38</strong> biographical events (<strong>~60%</strong> kinship, <strong>~40%</strong> biographical on <strong>94</strong> totals), making it the most <strong>genealogically entangled</strong> pair among the top ranks. <strong>Argentina–Uruguay</strong> is <strong>mixed</strong> (<strong>46</strong> vs <strong>59</strong>, or <strong>~44%</strong> kinship vs <strong>~56%</strong> biographical), consistent with a dense Rioplatense elite field in which family and professional or diplomatic circulation are both heavily documented. These contrasts are <strong>descriptive</strong>: kinship-heavy pairs point to family networks that actually cross borders in the scraped graph; biographical-heavy pairs capture elite circulation that <strong>may or may not</strong> coincide with kinship, but still registers transnational linkage in the corpus.</p>
<p>Historical narratives are <strong>suggestive</strong>, not testable here. The old <strong>Viceroyalty of Peru</strong> linked Chilean and Peruvian territories administratively; the <strong>War of the Pacific (1879–84)</strong> plausibly increased biographical cross-referencing between Chilean and Peruvian entries (military, exile, diplomatic elites). <strong>Argentina–Chile</strong> aligns with long-standing <strong>Andean–Southern Cone</strong> mobility, including nineteenth-century political exile (unitario currents toward Chile). <strong>Argentina–Uruguay</strong> fits a <strong>River Plate</strong> basin elite culture. The <strong>absence of a strong Argentina–Brazil</strong> edge among top pairs—despite geographic scale—is consistent with the idea that <strong>colonial administrative units and post-colonial circuits</strong> structure documentary elite ties more than continental proximity alone.</p>
<p>At the family level, <a href="#tbl-families-multinational" class="quarto-xref">Table&nbsp;5</a> highlights lineages such as <strong>Borrero</strong> (<strong>39</strong> members across <strong>four</strong> countries: Argentina, Chile, Colombia, Ecuador), <strong>Campero</strong> (<strong>24</strong> members; Argentina, Bolivia, Chile, Peru), and <strong>Sucre</strong> (<strong>11</strong> members; Argentina, Colombia, Ecuador, Venezuela). Their geographic footprints map onto <strong>Bolivarian and Gran-Colombia</strong> political geographies in ways that are <strong>consistent with</strong> post-independence elite continuity tied to colonial administrative networks—again, an interpretive alignment rather than a causal claim.</p>
<p>The Pacific-corridor pattern is not self-explanatory. Three mechanisms, operating at different scales, are consistent with it. At the <em>colonial</em> scale, the Viceroyalty of Peru imposed a common administrative field on territories that later became Chile, Peru, Bolivia, and—partially— Ecuador and Colombia: shared legal institutions, a single ecclesiastical hierarchy, and interlocking mining and commercial circuits created conditions for elite family formation that crossed what later became national borders. At the <em>republican</em> scale, the War of the Pacific (1879–84) did not dissolve elite ties between Chile and Peru—it intensified their biographical entanglement through military command, diplomatic negotiation, and forced exile, all of which generate Wikipedia cross-referencing independently of genealogy. At the <em>demographic</em> scale, the Andean corridor concentrated literate, Spanish-speaking populations in highland cities (Lima, Santiago, La Paz, Bogotá) that were closer to each other in travel time and cultural distance than to the Amazon basin or the Río de la Plata coast—creating a natural marriage market among notables.</p>
<p>None of these mechanisms is identified here; each is a hypothesis that cohort-level analysis, archival validation, or event-study designs using the War of the Pacific as a natural experiment could partially test. The absence of Argentina–Brazil from the top dyads is the strongest implicit test available: if geographic proximity alone drove the pattern, the two largest adjacent economies should dominate the matrix. They do not—which is consistent with the administrative-corridor hypothesis and inconsistent with a simple distance-decay model.</p>
<p><strong>H3 receives descriptive support</strong> for a Pacific–Andean and Southern Cone emphasis in this Wikipedia slice, with the critical caveat that <strong>biographical layers inflate</strong> some dyads relative to kinship and that mechanisms (mining, education, diplomacy) are not identified.</p>
</section>
<section id="h4-betweenness-and-brokerage" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="h4-betweenness-and-brokerage"><span class="header-section-number">4.4</span> H4: Betweenness and brokerage</h2>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-brokers" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-brokers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Top 15 individuals by betweenness centrality (multiplex graph; replication export).
</figcaption>
<div aria-describedby="tbl-brokers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Family</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Degree</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Betweenness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Luis Felipe Villarán</td>
<td style="text-align: left;">villarán</td>
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">410</td>
<td style="text-align: left;">517,714</td>
</tr>
<tr class="even">
<td style="text-align: left;">Walter Humala</td>
<td style="text-align: left;">humala</td>
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">557</td>
<td style="text-align: left;">473,134</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Luis Jaime Cisneros</td>
<td style="text-align: left;">cisneros</td>
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">364</td>
<td style="text-align: left;">391,641</td>
</tr>
<tr class="even">
<td style="text-align: left;">José Evaristo Uriburu</td>
<td style="text-align: left;">álvarez de arenales</td>
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">398</td>
<td style="text-align: left;">328,970</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pastor Obligado</td>
<td style="text-align: left;">obligado</td>
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">324</td>
<td style="text-align: left;">267,974</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guido Di Tella</td>
<td style="text-align: left;">di tella</td>
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">276</td>
<td style="text-align: left;">240,510</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patrocinio González Garrido</td>
<td style="text-align: left;">ortiz mena</td>
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">194</td>
<td style="text-align: left;">212,889</td>
</tr>
<tr class="even">
<td style="text-align: left;">Francisco Uriburu (hijo)</td>
<td style="text-align: left;">uriburu</td>
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">313</td>
<td style="text-align: left;">208,067</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuauhtémoc Cárdenas</td>
<td style="text-align: left;">cárdenas</td>
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">266</td>
<td style="text-align: left;">198,005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Demetrio Sodi de la Tijera</td>
<td style="text-align: left;">sodi</td>
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">169</td>
<td style="text-align: left;">188,638</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Roque Sáenz Peña</td>
<td style="text-align: left;">sáenz peña</td>
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">263</td>
<td style="text-align: left;">168,155</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guillermo Fernández de Soto</td>
<td style="text-align: left;">camacho</td>
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">219</td>
<td style="text-align: left;">163,071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jaime Arrubla Paucar</td>
<td style="text-align: left;">arrubla</td>
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">172</td>
<td style="text-align: left;">146,224</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rafael Roncagliolo</td>
<td style="text-align: left;">orbegoso</td>
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">235</td>
<td style="text-align: left;">144,958</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tomás Lander</td>
<td style="text-align: left;">lander</td>
<td style="text-align: left;">Venezuela</td>
<td style="text-align: right;">177</td>
<td style="text-align: left;">144,923</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>High betweenness is concentrated among a small set of individuals (<a href="#tbl-brokers" class="quarto-xref">Table&nbsp;6</a>): examples include <strong>Luis Felipe Villarán</strong> and <strong>Walter Humala</strong> (Peru), <strong>José Evaristo Uriburu</strong> (Argentina), and <strong>Cuauhtémoc Cárdenas</strong> (Mexico). <strong>H4 is descriptively supported</strong> in the sense that structural brokerage positions are identifiable in the augmented graph. We refrain from equating betweenness with political influence outside the documented network.</p>
<p>The concentration of betweenness among Peruvian and Argentine individuals warrants a structural interpretation. Peru’s over- representation at the top of the betweenness ranking—three of the top five individuals, including the highest-scoring node—is consistent with Lima’s historical role as the hub of the Viceregal network: a city that connected Andean silver routes to Atlantic commerce, Andean highland populations to coastal ports, and Bolivarian revolutionary circuits to conservative post-independence institutions. High betweenness, in this reading, is not a property of individuals per se but of structural positions inherited from colonial geography and reinforced by republican institution-building. The individuals who occupy these positions in the multiplex graph may do so because their biographies happen to articulate multiple institutional circuits—military, legal, party, educational—that are themselves geographically concentrated in Lima.</p>
<p>Argentina’s cluster of high-betweenness individuals (Uriburu, Obligado, Di Tella, Sáenz Peña) corresponds to the so-called “Generation of 1880”—the oligarchic coalition that built the Argentine state and simultaneously consolidated a marriage market, a party system, and a university system in Buenos Aires. That this generation produces high betweenness in the multiplex graph is mechanistically plausible: they were, empirically, the individuals who most intensively layered kinship onto institutional position. This is the structural signature of what Centeno (2002) calls the “limited war” elite—a group that achieved state consolidation not through mass mobilization but through network coordination among a small, interconnected stratum.</p>
</section>
<section id="gender-patterns" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="gender-patterns"><span class="header-section-number">4.5</span> Gender patterns</h2>
<p>The infobox pipeline does <strong>not</strong> encode sex; any gendered pattern must therefore be <strong>exploratory</strong>. <a href="#tbl-gender-heuristic" class="quarto-xref">Table&nbsp;7</a> applies an intentionally <strong>crude</strong> first-name heuristic (feminine-coded given names at the start of the string versus all others) to <code>metricas_centralidad.csv</code> for persons with positive degree. For <strong>Argentina</strong> and <strong>Colombia</strong>—the two largest samples—mean degree is similar across groups, while mean betweenness is <strong>lower</strong> for the feminine-coded group in <strong>Colombia</strong> and nearly identical in <strong>Argentina</strong>, underscoring <strong>subnational heterogeneity</strong> and the limits of name-based inference.</p>
<div class="cell" data-tbl-pos="!ht">
<div id="tbl-gender-heuristic" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="!ht">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gender-heuristic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Exploratory means by inferred first-name gender (heuristic labels only; not validated against civil-registry sex).
</figcaption>
<div aria-describedby="tbl-gender-heuristic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Gender group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean degree</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean betweenness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: left;">F (heuristic)</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">2124</td>
</tr>
<tr class="even">
<td style="text-align: left;">Argentina</td>
<td style="text-align: left;">M (heuristic)</td>
<td style="text-align: right;">1045</td>
<td style="text-align: right;">40.3</td>
<td style="text-align: right;">6935</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: left;">F (heuristic)</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">24.3</td>
<td style="text-align: right;">971</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colombia</td>
<td style="text-align: left;">M (heuristic)</td>
<td style="text-align: right;">1073</td>
<td style="text-align: right;">67.8</td>
<td style="text-align: right;">6770</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Interpretively, where <strong>degree</strong> in kin projections is <strong>high</strong> but <strong>betweenness</strong> in the multiplex graph is <strong>not</strong>, the pattern is <strong>consistent with</strong> women’s documented role as connectors in genealogical fields (marriage, descent) without equivalent placement on shortest paths that also traverse parties and universities—an alignment, at least narratively, with Lavrin’s (1990) emphasis on marriage as alliance and with Bourdieu’s (1996) distinction among forms of capital: <strong>genealogical visibility</strong> in Wikipedia need not translate into <strong>institutional brokerage</strong> in the augmented graph. A validated gender table (civil registers, manual coding, or external biographies) should replace <a href="#tbl-gender-heuristic" class="quarto-xref">Table&nbsp;7</a> before strong claims are attempted; the present discussion remains <strong>hypothesis-generating</strong> only.</p>
</section>
</section>
<section id="sec-discusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion and conclusion</h1>
<section id="heterogeneity-versus-a-single-latin-american-model" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="heterogeneity-versus-a-single-latin-american-model"><span class="header-section-number">5.1</span> Heterogeneity versus a single Latin American model</h2>
<p>Our results align with a <strong>heterogeneous Latin America</strong> thesis: elite kinship topologies are not isomorphic. Contrasting Paraguayan chain-like structures with Mexican or Colombian density resonates with institutionalist accounts of divergent state formation (Mahoney, 2010) even when measured through one digital source.</p>
</section>
<section id="the-pacific-corridor" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-pacific-corridor"><span class="header-section-number">5.2</span> The Pacific corridor</h2>
<p>The Pacific–Andean emphasis in cross-border weights (<a href="#tbl-pairs" class="quarto-xref">Table&nbsp;4</a>; <a href="#fig-mapa-heatmap" class="quarto-xref">Figure&nbsp;4</a>) is <strong>not reducible to geographic proximity alone</strong>. Bolivia and Ecuador are proximate to several large republics yet do not dominate the top dyads in this corpus; the pattern therefore aligns more closely with <strong>historical administrative and biographical pathways</strong> than with a simple distance decay model. Viceregal structures once centered on Lima linked Andean and coastal spaces into a common political field; the War of the Pacific (1879–84) further entangled Chilean and Peruvian elites through conflict, exile, and subsequent documentation in biographical fields. <strong>Caveat:</strong> biographical signals—death place, residence, occupation—inflate certain pairs relative to kinship alone; for Chile–Peru, <strong>69%</strong> of counted events are biographical (<strong>81</strong> of <strong>117</strong>) and <strong>31%</strong> kinship (<strong>36</strong> of <strong>117</strong>), which may partly reflect Chilean encyclopedic attention to Peruvian figures and exiles after 1879, not only cross-border genealogy. By contrast, Argentina–Chile is <strong>predominantly kinship-weighted</strong> (<strong>60%</strong> kinship, <strong>40%</strong> biographical on <strong>94</strong> events), consistent with denser genealogical entanglement (including historically documented migration and political exile corridors). Argentina–Uruguay is <strong>mixed</strong> (<strong>44%</strong> kinship, <strong>56%</strong> biographical on <strong>105</strong> events), consistent with a shared Rioplatense cultural field in which family and professional circulation are both visible. The <strong>absence of Argentina–Brazil</strong> among the strongest pairs is itself descriptive: elite ties in this archive appear <strong>corridor-specific</strong> rather than continental, which is consistent with colonial administrative legacies and Rioplatense cultural circuits more than with uniform neighborhood effects across Latin America. This pattern should be read as <strong>policy- and archive-relevant</strong> (where transnational elite coordination appears in a documentary corpus), not as proof of contemporary diplomatic alignment.</p>
</section>
<section id="alternative-explanations-and-their-limits" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="alternative-explanations-and-their-limits"><span class="header-section-number">5.3</span> Alternative explanations and their limits</h2>
<p>Three alternative explanations must be addressed before treating the observed patterns as informative.</p>
<p><em>Wikipedia visibility bias</em> is the most serious. If some families are documented in Wikipedia simply because they are more famous— rather than because they are more networked—then high degree could reflect celebrity rather than structural position. Two observations partially mitigate this concern. First, the negative correlation between degree and endogamy (H1) would not follow from a pure visibility story: celebrity families are not systematically more exogamous than obscure ones. Second, the topological variation across countries—chain in Paraguay, star in Chile, web in Argentina— is not reducible to differential Wikipedia coverage, since all countries are drawn from the same Spanish-language corpus under comparable extraction rules. Visibility bias inflates all graphs equally; it cannot explain <em>differential</em> topology.</p>
<p><em>Demographic structure</em> offers a second alternative: countries with larger populations should produce denser networks simply by having more nodes. Mexico and Argentina are the most populous countries in the corpus and do show dense webs—but Chile, with fewer than half Mexico’s population, also shows a dense star structure, while Bolivia and Ecuador, with smaller corpora, show fragmentation rather than simple sparsity. The topology classification is not monotonically predicted by corpus size. Paraguay’s linear chain emerges from the smallest national corpus (n=21), which is consistent with patrimonial consolidation rather than with any density artifact.</p>
<p><em>Random network formation</em> is the null hypothesis that neither analysis explicitly tests. An Erdős–Rényi random graph with the same degree sequence as the Chilean subgraph would not produce a star topology; star formation requires a generative process (preferential attachment, or a founding lineage with historically higher documentation probability) that is itself non-random. Future work using configuration models or exponential random graph models (ERGMs) could formalize this comparison; the present analysis treats topology classification as interpretive, not inferential.</p>
</section>
<section id="wikipedia-as-archive-not-mirror" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="wikipedia-as-archive-not-mirror"><span class="header-section-number">5.4</span> Wikipedia as archive, not mirror</h2>
<p>Reframing Wikipedia as an <strong>archive of collective documentation</strong> clarifies epistemic status: we study who is repeatedly named and linked—not the full elite stratum of each society. That move aligns with computational social science cautions about digital trace data (Lazer et al., 2014) and with calls for transparency in algorithm-assisted history.</p>
</section>
<section id="ethics-and-public-use" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="ethics-and-public-use"><span class="header-section-number">5.5</span> Ethics and public use</h2>
<p>Wikipedia biographies are public, but aggregate reporting should avoid gratuitous emphasis on living persons without public-interest justification. We report aggregate patterns and historically distant examples where possible.</p>
</section>
<section id="toward-causal-identification-design-proposals" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="toward-causal-identification-design-proposals"><span class="header-section-number">5.6</span> Toward causal identification: design proposals</h2>
<p>The observational design of this study precludes causal inference, but the data infrastructure supports at least three identification gestures that future work could pursue.</p>
<p><strong>Cohort analysis.</strong> The corpus contains birth years for 92.9% of individuals. Slicing the network by birth decade (e.g., 1800–1829, 1830–1859, …) would allow testing whether the closure–reach trade-off (H1) intensified during periods of state consolidation and relaxed during revolutionary disruptions. If endogamy rates rose in Chile in the decades following the 1833 Constitution and fell after the 1891 Civil War, that would be consistent with the institutional mechanism proposed under H1—and inconsistent with a purely demographic explanation.</p>
<p><strong>The War of the Pacific as a natural experiment.</strong> The 1879–84 conflict introduced an exogenous shock to Chilean–Peruvian elite relations: diplomatic expulsion, property confiscation, and forced migration disrupted pre-war kinship networks while simultaneously generating new biographical cross-referencing (military records, exile accounts, peace negotiations). A difference-in-differences design comparing Chile–Peru cross-border kinship edges (pre- vs. post-1879, using birth year as a proxy for cohort) against a control corridor (e.g., Argentina–Uruguay, which experienced no equivalent shock) could test whether the biographical-heavy Chile–Peru dyad is a post-war artifact of documentary entanglement rather than a pre-war kinship structure. This design is feasible with the existing data; it is a priority for the next iteration of this project.</p>
<p><strong>Geographic constraints as instruments.</strong> The Andes mountain range created differential travel costs across the corridor. Pairs of cities at similar distances but separated by different geographic barriers (Andean passes vs.&nbsp;coastal routes) should show different kinship edge densities if physical access shaped the marriage market. This geographic instrument—variation in natural barriers to elite mobility—could partially identify the geographic component of the transnational corridor effect, separating it from the administrative and cultural components.</p>
<p>None of these designs is executed here. We flag them not as post-hoc rationalizations but as genuine implications of the data infrastructure already built—implications that make the present descriptive contribution a foundation rather than an endpoint.</p>
</section>
<section id="concluding-remarks" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="concluding-remarks"><span class="header-section-number">5.7</span> Concluding remarks</h2>
<p>Drawing on Wikipedia-derived kinship networks for <strong>6,169</strong> Latin American notables and <strong>8,201</strong> matched kinship edges (embedded in a larger multiplex graph for centrality), we document substantial cross-national heterogeneity in elite family structure. Descriptive patterns align <strong>directionally</strong> with four working hypotheses—closure and concentration, topology and stylized regime narratives, Pacific-leaning transnational weights, and identifiable betweenness brokers—while remaining strictly <strong>observational</strong>. The most robust takeaway is <strong>diversity</strong>: elite kinship in Latin America does not reduce to a single network form. Secondary regularities—Pacific-Andean prominence in cross-border weights (<a href="#tbl-pairs" class="quarto-xref">Table&nbsp;4</a>), gendered degree–betweenness splits—warrant further investigation with richer data.</p>
<p>We close with a practical observation: <strong>digital genealogies</strong> increasingly shape public imaginaries of elite connection. Scholarly use of such sources demands methodological transparency and humility about whose ties get documented—and whose remain invisible.</p>
<p>The broader implication extends beyond Latin American historiography. Elite kinship networks documented in public digital archives are increasingly legible to journalists, activists, and political opponents—not only to scholars. The families that inscribed themselves most densely in Wikipedia are also the families most vulnerable to network-based accountability journalism (cross-referencing kinship with corporate boards, public contracts, and party donations). Understanding the structure of the documentary elite field is therefore not merely an academic exercise: it is a prerequisite for assessing the political consequences of open genealogical data. Where network closure and institutional concentration coincide— as they do in several of the polities analyzed here—the transparency afforded by digital archives may paradoxically reinforce elite salience by making visible precisely those connections that elite families have long relied upon but rarely had to defend publicly.</p>
</section>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<p>Balmori, D., Voss, S., &amp; Wortman, M. (1984). <em>Notable Family Networks in Latin America</em>. University of Chicago Press.</p>
<p>Bourdieu, P. (1996). <em>The State Nobility: Elite Schools in the Field of Power</em>. Stanford University Press.</p>
<p>Centeno, M. A. (2002). <em>Blood and Debt: War and the Nation-State in Latin America</em>. Pennsylvania State University Press.</p>
<p>Granovetter, M. S. (1973). The strength of weak ties. <em>American Journal of Sociology</em>, <em>78</em>(6), 1360–1380.</p>
<p>Lazer, D., Kennedy, R., King, G., &amp; Vespignani, A. (2014). The parable of Google Flu: Traps in big data analysis. <em>Science</em>, <em>343</em>(6176), 1203–1205.</p>
<p>Lavrin, A. (Ed.). (1990). <em>Sexuality and Marriage in Colonial Latin America</em>. University of Nebraska Press.</p>
<p>Mahoney, J. (2010). <em>Colonialism and Postcolonial Development: Spanish America in Comparative Perspective</em>. Cambridge University Press.</p>
<p>Mosca, G. (1939). <em>The Ruling Class</em>. McGraw-Hill. (Original work published 1896)</p>
<p>Padgett, J. F., &amp; Ansell, C. K. (1993). Robust action and the rise of the Medici, 1400–1434. <em>American Journal of Sociology</em>, <em>98</em>(6), 1259–1319.</p>
<p>Pareto, V. (1991). <em>The Rise and Fall of Elites: An Application of Theoretical Sociology</em>. Transaction Publishers. (Original work published 1901)</p>
<p>Weber, M. (1978). <em>Economy and Society</em> (G. Roth &amp; C. Wittich, Eds.). University of California Press.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>